# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 320f0fdade6655df43a0229386baa32f49db2be8b648c8bf597536242ab9fcd0f3fcfb5480f41de1e31a14820f5177cb179011b3f67ba9e1f7fddebb4a943161

test:
  secret_key_base: dfd4a82b7080983f8ee8113ba12c7b3d2b5f15271d7a1d6c9855d2385466e34550f877b84012783b92d289479124481975664a345393fe6e52b70dfc1b097f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
